name: Compile and Test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1.0.6
        with:
          version: nightly

      - name: Run tests
        run: forge test --no-match-contract Integration -vvv
      
      - name: Run Integration tests
        run: forge test --match-contract Integration --fork-url https://rpc.ankr.com/eth -vvv
        